name: jpj_info
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  stilo: ^2.0.0
  flutter_easyloading: ^3.0.3
  pin_code_fields: ^7.3.0
  flutter_countdown_timer: ^4.1.0
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  shared_preferences: ^2.0.13
  flutter_svg_provider: ^1.0.3
  maps_launcher: ^2.0.1
  flutter_slidable: ^1.2.0
  url_launcher: ^6.0.20
  image_picker: ^0.8.5
  flutter_map: ^0.14.0
  qr_flutter: ^4.0.0
  mobile_scanner: ^1.0.0
  latlong2: ^0.8.1
  launch_review: ^3.0.1
  external_app_launcher: ^2.0.2
  badges: ^2.0.3
  geolocator: ^9.0.2
  advance_pdf_viewer: any
  video_thumbnail: ^0.5.3
  flexible_scrollbar: ^0.1.2
  path: ^1.8.1
  flutter_share: ^2.0.0
  # workmanager: ^0.5.0
  # flutter_local_notifications: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/login_bg.png
    - images/main_bg.png
    - images/myjpj_logo_large.png
    - images/my_jpj_icon.png
    - images/info_tooltip_btn.png
    - images/vector/btm_profile_icon.svg
    - images/vector/btm_profile_icon_2.svg
    - images/vector/btm_main_menu_icon.svg
    - images/vector/btm_home_icon.svg
    - images/vector/setting_icon_lang.svg
    - images/vector/faq_icon.svg
    - images/vector/en_lang_icon.svg
    - images/vector/ms_lang_icon.svg
    - images/vector/inbox_icon.svg
    - images/vector/share_icon.svg
    - images/vector/logout_icon.svg
    - images/vector/arrow_down_icon.svg
    - images/icon/black_list_icon.png
    - images/icon/change_password.png
    - images/icon/demerit_point_icon.png
    - images/icon/directory_icon.png
    - images/icon/driving_license_icon.png
    - images/icon/eaduan_icon.png
    - images/icon/ebit_icon.png
    - images/icon/ezypay_icon.png
    - images/icon/feedback_icon.png
    - images/icon/jpjeq_icon.png
    - images/icon/latest_number_icon.png
    - images/icon/lkm_icon.png
    - images/icon/online_transaction_icon.png
    - images/icon/payment_history_icon.png
    - images/icon/test_result_icon.png
    - images/icon/ticket_icon.png
    - images/icon/tnc_icon.png
    - images/icon/update_profile_icon.png
    - images/icon/vehicle_list_icon.png
    - images/icon/jpjehadir.png
    - images/flag/n1.png
    - images/flag/n10.png
    - images/flag/n11.png
    - images/flag/n12.png
    - images/flag/n13.png
    - images/flag/n14.png
    - images/flag/n15.png
    - images/flag/n16.png
    - images/flag/n2.png
    - images/flag/n3.png
    - images/flag/n4.png
    - images/flag/n5.png
    - images/flag/n6.png
    - images/flag/n7.png
    - images/flag/n8.png
    - images/flag/n9.png
    - images/vector/vehicle_list_icon.svg
    - images/vector/update_profile_icon.svg
    - images/vector/tnc_icon.svg
    - images/vector/feedback_icon.svg
    - images/vector/change_password_icon.svg
    - json/summons.json
    - json/jpj_location.json
    - images/vector/location_icon.svg
    - json/messages.json
    - json/transaction_history.json
    - images/amazon_logo.png
    - images/google_pay_logo.png
    - images/applepay_logo.png
    - images/paypal_logo.png
    - images/american_express_logo.png
    - images/visa_logo.png
    - images/mastercard_logo.png
    - images/icon/jpjeq_branch_icon.png
    - images/icon/jpjeq_transaction_icon.png
    - images/icon/jpjeq_info_icon.png
    - images/icon/eaduan_using_phone_icon.png
    - images/icon/eaduan_double_line_overtake_icon.png
    - images/icon/eaduan_left_overtake_icon.png
    - images/icon/eaduan_skip_queue_icon.png
    - images/icon/eaduan_emergency_lane_icon.png
    - images/icon/eaduan_traffic_light_icon.png
    - images/main_bg_half.png
    - images/jpj_official_icon.png
    - images/icon/eaduan_dark_tint_icon.png
    - images/icon/eaduan_fancy_plat_icon.png
    - images/icon/eaduan_not_wearing_seatbelt_icon.png
    - images/submit_image.png
    - json/eaduan.json
    - images/icon/ehadir_comittee_icon.png
    - images/icon/ehadir_activity_icon.png
    - images/icon/ehadir_main_icon.png
    - images/ehadir_attending_activity_figure.png
    - images/ehadir_man_and_clock.png
    - images/ehadir_men_at_work.png
    - images/icon/ehadir_add_comittee_icon.png
    - images/icon/ehadir_manual_register_icon.png
    - images/icon/ehadir_add_attendee_icon.png
    - images/icon/ehadir_new_activity_icon.png
    - images/icon/ehadir_scan_qr_icon.png
    - json/ehadir_event.json
    - json/ehadir_activity_list.json
    - images/jpj_flag.png
    - images/jpjeq_cancel_number.png
    - images/jpjeq_people_at_counter.png
    - images/jpjeq_people_queue.png
    - images/icon/refresh_icon.png
    - images/flag/ms-flag-icon.png
    - images/flag/en-flag-icon.png
    - images/vector/btm_directory_icon.svg
    - images/vector/btm_inbox_icon.svg
    - images/splashscreen_bg.png
    - images/myjpj_logo_large_backup.png
    - images/icon/ehadir/ehadir_main_icon_activity.png
    - images/icon/ehadir/ehadir_main_icon_comitee.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: CustomMessagesIcon
      fonts:
        - asset: fonts/CustomMessagesIcon.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Light.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Thin.ttf
          weight: 300
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900
    - family: MaShanZheng
      fonts:
        - asset: fonts/MaShanZheng-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
